[project]
name = "slambot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clang-format>=20.1.0",
    "cmake>=4.0.0",
    "conan>=2.15.1",
    "ninja>=1.11.1.4",
]
